# Uncomment the next line to define a global platform for your project
platform :osx, '10.12'

target 'SafeEject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SafeEject
  pod 'ORSSerialPort', '~> 2.1.0'
  pod 'SwiftLint'

  target 'SafeEjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SafeEjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
